"""Initial schema creation

Revision ID: 1350b0ae0e6f
Revises: 
Create Date: 2026-01-13 18:45:11.779497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1350b0ae0e6f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seasons',
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('month_start', sa.Integer(), nullable=False),
    sa.Column('month_end', sa.Integer(), nullable=False),
    sa.Column('temperature_min_celsius', sa.Integer(), nullable=True),
    sa.Column('temperature_max_celsius', sa.Integer(), nullable=True),
    sa.Column('humidity_percent', sa.Integer(), nullable=True),
    sa.Column('rainfall_mm', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('best_for_activities', sa.String(length=255), nullable=True),
    sa.Column('is_tourist_season', sa.Boolean(), nullable=True),
    sa.Column('is_peak_season', sa.Boolean(), nullable=True),
    sa.Column('crowding_level', sa.Enum('low', 'moderate', 'high', name='crowding_level'), nullable=True),
    sa.Column('vegetation_status', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('season_id')
    )
    op.create_index(op.f('ix_seasons_name'), 'seasons', ['name'], unique=True)
    op.create_index(op.f('ix_seasons_season_id'), 'seasons', ['season_id'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.Enum('admin', 'editor', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('events',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.Enum('festival', 'fair', 'ceremony', 'cultural', name='event_type'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('is_annual', sa.Boolean(), nullable=True),
    sa.Column('expected_attendance', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=11, scale=8), nullable=True),
    sa.Column('organizing_body', sa.String(length=255), nullable=True),
    sa.Column('contact_person', sa.String(length=100), nullable=True),
    sa.Column('contact_phone', sa.String(length=20), nullable=True),
    sa.Column('contact_email', sa.String(length=100), nullable=True),
    sa.Column('entry_fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_free', sa.Boolean(), nullable=True),
    sa.Column('parking_available', sa.Boolean(), nullable=True),
    sa.Column('accommodation_nearby', sa.Boolean(), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('status', sa.Enum('upcoming', 'ongoing', 'completed', name='event_status'), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_events_event_id'), 'events', ['event_id'], unique=False)
    op.create_index(op.f('ix_events_name'), 'events', ['name'], unique=False)
    op.create_table('mythological_sites',
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('mythology', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('legend_source', sa.String(length=255), nullable=True),
    sa.Column('historical_period', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=11, scale=8), nullable=True),
    sa.Column('cultural_significance', sa.Text(), nullable=True),
    sa.Column('archaeological_value', sa.Text(), nullable=True),
    sa.Column('accessibility', sa.Enum('easily_accessible', 'moderate', 'difficult', name='accessibility_level'), nullable=True),
    sa.Column('guide_available', sa.Boolean(), nullable=True),
    sa.Column('best_time_to_visit', sa.String(length=100), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('site_id')
    )
    op.create_index(op.f('ix_mythological_sites_name'), 'mythological_sites', ['name'], unique=False)
    op.create_index(op.f('ix_mythological_sites_site_id'), 'mythological_sites', ['site_id'], unique=False)
    op.create_table('places',
    sa.Column('place_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.Enum('place', 'landmark', 'viewpoint', 'parking', name='place_category'), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=11, scale=8), nullable=True),
    sa.Column('elevation_meters', sa.Integer(), nullable=True),
    sa.Column('entry_fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('entry_fee_currency', sa.String(length=3), nullable=True),
    sa.Column('best_time_to_visit', sa.String(length=100), nullable=True),
    sa.Column('average_visit_duration_hours', sa.Integer(), nullable=True),
    sa.Column('accessibility', sa.Enum('easily_accessible', 'moderate', 'difficult', name='accessibility_level'), nullable=True),
    sa.Column('parking_available', sa.Boolean(), nullable=True),
    sa.Column('public_restrooms', sa.Boolean(), nullable=True),
    sa.Column('food_nearby', sa.Boolean(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('place_id')
    )
    op.create_index(op.f('ix_places_name'), 'places', ['name'], unique=False)
    op.create_index(op.f('ix_places_place_id'), 'places', ['place_id'], unique=False)
    op.create_table('temples',
    sa.Column('temple_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('deity', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('architectural_style', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=11, scale=8), nullable=True),
    sa.Column('age_years', sa.Integer(), nullable=True),
    sa.Column('is_active_pilgrimage', sa.Boolean(), nullable=True),
    sa.Column('main_festival', sa.String(length=100), nullable=True),
    sa.Column('festival_date', sa.String(length=50), nullable=True),
    sa.Column('pooja_timings', sa.String(length=255), nullable=True),
    sa.Column('entry_fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('parking_available', sa.Boolean(), nullable=True),
    sa.Column('prasad_available', sa.Boolean(), nullable=True),
    sa.Column('priest_name', sa.String(length=100), nullable=True),
    sa.Column('priest_contact', sa.String(length=20), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('temple_id')
    )
    op.create_index(op.f('ix_temples_name'), 'temples', ['name'], unique=False)
    op.create_index(op.f('ix_temples_temple_id'), 'temples', ['temple_id'], unique=False)
    op.create_table('galleries',
    sa.Column('gallery_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('gallery_type', sa.Enum('photos', 'videos', '360photos', name='gallery_type'), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('place_id', sa.Integer(), nullable=True),
    sa.Column('temple_id', sa.Integer(), nullable=True),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.event_id'], ),
    sa.ForeignKeyConstraint(['place_id'], ['places.place_id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['mythological_sites.site_id'], ),
    sa.ForeignKeyConstraint(['temple_id'], ['temples.temple_id'], ),
    sa.PrimaryKeyConstraint('gallery_id')
    )
    op.create_index(op.f('ix_galleries_gallery_id'), 'galleries', ['gallery_id'], unique=False)
    op.create_table('reviews',
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('review_type', sa.Enum('place', 'temple', 'site', 'event', name='review_type'), nullable=False),
    sa.Column('place_id', sa.Integer(), nullable=True),
    sa.Column('temple_id', sa.Integer(), nullable=True),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('visitor_name', sa.String(length=100), nullable=False),
    sa.Column('visitor_email', sa.String(length=100), nullable=False),
    sa.Column('visit_date', sa.Date(), nullable=True),
    sa.Column('visit_duration_hours', sa.Integer(), nullable=True),
    sa.Column('value_for_money', sa.Integer(), nullable=True),
    sa.Column('cleanliness_rating', sa.Integer(), nullable=True),
    sa.Column('crowd_rating', sa.Integer(), nullable=True),
    sa.Column('accessibility_rating', sa.Integer(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('helpful_count', sa.Integer(), nullable=True),
    sa.Column('unhelpful_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='review_status'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.event_id'], ),
    sa.ForeignKeyConstraint(['place_id'], ['places.place_id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['mythological_sites.site_id'], ),
    sa.ForeignKeyConstraint(['temple_id'], ['temples.temple_id'], ),
    sa.PrimaryKeyConstraint('review_id')
    )
    op.create_index(op.f('ix_reviews_review_id'), 'reviews', ['review_id'], unique=False)
    op.create_table('seasonal_availabilities',
    sa.Column('availability_id', sa.Integer(), nullable=False),
    sa.Column('place_id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('is_accessible', sa.Boolean(), nullable=False),
    sa.Column('accessibility_notes', sa.Text(), nullable=True),
    sa.Column('crowding_level', sa.Enum('low', 'moderate', 'high', name='crowding_level'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['place_id'], ['places.place_id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.season_id'], ),
    sa.PrimaryKeyConstraint('availability_id'),
    sa.UniqueConstraint('place_id', 'season_id', name='unique_place_season')
    )
    op.create_index(op.f('ix_seasonal_availabilities_availability_id'), 'seasonal_availabilities', ['availability_id'], unique=False)
    op.create_table('site_events',
    sa.Column('site_event_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.event_id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['mythological_sites.site_id'], ),
    sa.PrimaryKeyConstraint('site_event_id'),
    sa.UniqueConstraint('site_id', 'event_id', name='unique_site_event')
    )
    op.create_index(op.f('ix_site_events_site_event_id'), 'site_events', ['site_event_id'], unique=False)
    op.create_table('temple_events',
    sa.Column('temple_event_id', sa.Integer(), nullable=False),
    sa.Column('temple_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.event_id'], ),
    sa.ForeignKeyConstraint(['temple_id'], ['temples.temple_id'], ),
    sa.PrimaryKeyConstraint('temple_event_id'),
    sa.UniqueConstraint('temple_id', 'event_id', name='unique_temple_event')
    )
    op.create_index(op.f('ix_temple_events_temple_event_id'), 'temple_events', ['temple_event_id'], unique=False)
    op.create_table('gallery_images',
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.Column('gallery_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('photographer', sa.String(length=100), nullable=True),
    sa.Column('image_order', sa.Integer(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['gallery_id'], ['galleries.gallery_id'], ),
    sa.PrimaryKeyConstraint('image_id')
    )
    op.create_index(op.f('ix_gallery_images_image_id'), 'gallery_images', ['image_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gallery_images_image_id'), table_name='gallery_images')
    op.drop_table('gallery_images')
    op.drop_index(op.f('ix_temple_events_temple_event_id'), table_name='temple_events')
    op.drop_table('temple_events')
    op.drop_index(op.f('ix_site_events_site_event_id'), table_name='site_events')
    op.drop_table('site_events')
    op.drop_index(op.f('ix_seasonal_availabilities_availability_id'), table_name='seasonal_availabilities')
    op.drop_table('seasonal_availabilities')
    op.drop_index(op.f('ix_reviews_review_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_galleries_gallery_id'), table_name='galleries')
    op.drop_table('galleries')
    op.drop_index(op.f('ix_temples_temple_id'), table_name='temples')
    op.drop_index(op.f('ix_temples_name'), table_name='temples')
    op.drop_table('temples')
    op.drop_index(op.f('ix_places_place_id'), table_name='places')
    op.drop_index(op.f('ix_places_name'), table_name='places')
    op.drop_table('places')
    op.drop_index(op.f('ix_mythological_sites_site_id'), table_name='mythological_sites')
    op.drop_index(op.f('ix_mythological_sites_name'), table_name='mythological_sites')
    op.drop_table('mythological_sites')
    op.drop_index(op.f('ix_events_name'), table_name='events')
    op.drop_index(op.f('ix_events_event_id'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_seasons_season_id'), table_name='seasons')
    op.drop_index(op.f('ix_seasons_name'), table_name='seasons')
    op.drop_table('seasons')
    # ### end Alembic commands ###
